---
version: "3.3"
services:
  pmp:
    build: .
    image: postlu/pmp:latest
    restart: unless-stopped
    container_name: pmp
    hostname: pmp
    ports:
      - "5522:5522"
      - "7070:7070"
      - "7272:7272"
      - "7273:7273"
    # environment:
    #   - PMP_UPGRADE=1
    volumes:
      - ./data/pmp:/data
      # DEVEL
      # - ./entrypoint.sh:/entrypoint.sh
